// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_timeLbl;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_secLbl;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_dateLbl;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_wdayLbl;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_BIG);
LV_FONT_DECLARE(ui_font_MED);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
